- name: Install supervisor
  yum:
    name: supervisor
    state: present

- name: Create Daphne supervisor conf file
  copy:
    dest: /etc/supervisord.d/daphne.ini
    content: |
      [program:daphne]
      command=/var/www/{{ project_name }}/.venv/bin/daphne -u /var/www/{{ project_name }}/daphne.sock {{ project_name }}.asgi:application
      directory=/var/www/{{ project_name }}
      user=nginx
      autostart=true
      autorestart=true
      stderr_logfile=/var/log/daphne.err.log
      stdout_logfile=/var/log/daphne.out.log

- name: Enable and start supervisord
  systemd:
    name: supervisord
    enabled: yes
    state: restarted

#- name: Manage the state of program to be in started state
#  community.general.supervisorctl:
#    name: daphne
#    state: restarted
