- name: Create Daphne systemd service
  copy:
    dest: /etc/systemd/system/daphne.service
    content: |
      [Unit]
      Description=Daphne Service
      After=network.target

      [Service]
      User=nginx
      Group=nginx
      WorkingDirectory=/var/www/{{ project_name }}
      ExecStart=/var/www/{{ project_name }}/.venv/bin/daphne -u /var/www/{{ project_name }}/daphne.sock {{ project_name }}.asgi:application

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Daphne
  systemd:
    daemon_reload: yes
    name: daphne
    enabled: yes
    state: restarted
