- name: Configure Nginx for Daphne
  copy:
    dest: /etc/nginx/sites-available/{{ project_name }}
    content: |
      server {
          listen 80;
          server_name {{ domain_name }};

          location /static/ {
              alias /home/ubuntu/{{ project_name }}/static/;
          }

          location / {
              proxy_pass http://unix:/home/ubuntu/{{ project_name }}/daphne.sock;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_redirect off;
          }
      }

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/{{ project_name }}
    dest: /etc/nginx/sites-enabled/{{ project_name }}
    state: link
    force: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
