- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Create PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"

- name: Create PostgreSQL database
  become_user: postgres
  postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
